### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xassembly#4]
In order to launch we should have:

- [ ] LANGUAGE as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [ ] at least 10 problems
- [ ] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-LANGUAGE.md`)
- [ ] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [ ] add track implementors and other designated nitpickers as mentors to the track
- [ ] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by kytrinyx** [comment]
It's been nearly 3 years since this track was requested. So far all the commits (over 30) have been structural, to keep it in line with the changes on Exercism.

If I don't hear any strong counter-arguments in the next week, I'm going to go ahead and delete this, and wait until someone requests it again in https://github.com/exercism/request-new-language-track
